name: Deploy
on: push
permissions: 
  contents: write
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: node build.cjs
      - name: Minify
        run: node mini.cjs
      - name: Publish pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: public
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com